apiVersion: v1
kind: Service
metadata:
  name: post-mysql-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None

---

apiVersion: v1
kind: Endpoints
metadata:
  name: post-mysql-service
subsets:
  - addresses:
      - ip: 192.168.0.46
    ports:
      - port: 13309